
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "landing page",
  description: "Generated by create next app",
};


export default function LandingPageLayout({ children }: LayoutProps<"/">) {
  return (
    
     <div >
     
   
<div className="mt-30">
     {children}
</div>
      
 
        </div>
         
  )
}