
import Header from "@/component/header";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "landing page",
  description: "Generated by create next app",
};


export default function LandingPageLayout({ children }: LayoutProps<"/">) {
  return (
    
     <div >
     
  
   
  
<div className=" bg-slate-950 min-h-screen">
     <div
        aria-hidden="true"
        className="pointer-events-none absolute inset-0 overflow-hidden"
      >
        <div className="absolute -right-40 -top-40 h-96 w-96 rounded-full bg-yellow-400/10 blur-3xl" />
        <div className="absolute -left-40 top-1/2 h-96 w-96 rounded-full bg-orange-500/10 blur-3xl" />
        <div className="absolute bottom-0 right-1/3 h-72 w-72 rounded-full bg-yellow-500/5 blur-3xl" />
      </div>
     <Header />
     {children}
</div>
      
 
        </div>
         
  )
}